#!/usr/bin/env bash
#Show a story
input="/etc/passwd"
while read -r line; do
    USERNAME=$(echo "$line" | cut -d ":" -f 1)
    GROUP_ID=$(echo "$line" | cut -d ":" -f 4)
    HOME_DIRECTORY=$(echo "$line" | cut -d ":" -f 6)
    COMMAND=$(echo "$line" | cut -d ":" -f 7)
    USERID=$(echo "$line" | cut -d ":" -f 3)
    PASSWORD=$(echo "$line" | cut -d ":" -f 2)
    USERIDINFO=$(echo "$line" | cut -d ":" -f 5)
  echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"
done < $input
